### ISSUE TITLE
not deploying stack

### ISSUE THREAD

**Issue by bennergarrett** [youyo/aws-sam-action#4]
in the same deploy section it will get to the end and display
`Deploy this changeset? [y/N]: Aborted!`
which then causes the stack to stay in review on Cloudformation and never deploy

**Comment by bennergarrett** [comment]
found the issue, there were some complaints about it running without the changes by default.  Just add `--no-confirm-changeset` to the deploy options

**Comment by youyo** [comment]
fix #5
